# You also need the Dockerfile_Server file, put it in the same directory as this file.
# Build and create a container with: docker-compose up -d --build
# You may set the version of the server when an update is released, see "args"
#
# Attach to the container with: docker-compose exec lunamultiplayer /bin/ash
version: '3.3'
services:
    lunamultiplayer:
        image: lunamultiplayer:local
        build:
          context: ./
          dockerfile: Dockerfile_Server_Debian
        container_name: lmpsrvRSS
        environment:
            - TZ=CET
        ports:
            - '8801:8801/udp'
            # uncomment to enable website
            # - '8900:8900'
        volumes:
            - '/opt/LunaMultiplayerRSS/Config:/LMPServer/Config'
            - '/opt/LunaMultiplayerRSS/Universe:/LMPServer/Universe'
            - '/opt/LunaMultiplayerRSS/Plugins:/LMPServer/Plugins'
            - '/opt/LunaMultiplayerRSS/logs:/LMPServer/logs'
        restart: unless-stopped

    lunamultiplayer-nonprod:
        image: lunamultiplayer-nonprod:local
        build:
          context: ./
          dockerfile: Dockerfile_Server_Debian_nonprod
        container_name: lmpsrvRSSnonprod
        environment:
            - TZ=CET
        ports:
            - '8802:8802/udp'
            # uncomment to enable website
            # - '8900:8900'
        volumes:
            - '/opt/LunaMultiplayerRSSnonprod/Config:/LMPServer/Config'
            - '/opt/LunaMultiplayerRSSnonprod/Universe:/LMPServer/Universe'
            - '/opt/LunaMultiplayerRSSnonprod/Plugins:/LMPServer/Plugins'
            - '/opt/LunaMultiplayerRSSnonprod/logs:/LMPServer/logs'
        restart: unless-stopped
